version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: board
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: springboot-app
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SECRET_KEY: SecretK3ySecretK3ySecretK3ySecretK3ySecretK3ySecretK3y
      FILE_PATH: /app/files/
      FILE_URL: http://localhost:4000/file/
    depends_on:
      - db
    volumes:
      - ./uploads:/app/files/

volumes:
  mysql-data:
