apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: app
          image: timulys/springboot-app:latest
          ports:
            - containerPort: 4000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SECRET_KEY
              value: SecretK3ySecretK3ySecretK3ySecretK3ySecretK3ySecretK3y
            - name: FILE_PATH
              value: /app/files/
            - name: FILE_URL
              value: http://localhost:4000/file/
