name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write # <--- 이 줄을 추가하세요

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: timulys/springboot-app:${{ github.sha }} # 자동 sha hash 태그 입력

      - name: Update deployment YAML with new image tag
        run: |
          sed -i 's|image: timulys/springboot-app:.*|image: timulys/springboot-app:${{ github.sha }}|' k8s/deployment-app.yaml

      - name: Commit and Push updated manifest
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add k8s/deployment-app.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
